from pathlib import Path
from typing import Optional, List, Dict, Any
import pandas as pd
import numpy as np

from app.training import DATA_FILE, MENU_TYPES, WEEKDAYS, load_and_validate_data
from app.schemas import DashboardSummary


def get_historical_dataframe() -> pd.DataFrame:
    return load_and_validate_data(DATA_FILE)


def get_dashboard_summary(waste_summary: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    df = get_historical_dataframe()

    total_records = len(df)
    unique_dates = df["Date"].nunique()
    date_min = df["Date"].min().strftime("%Y-%m-%d")
    date_max = df["Date"].max().strftime("%Y-%m-%d")

    avg_daily_demand = round(float(df.groupby("Date")["Actual meals sold"].sum().mean()), 1)
    menu_totals = df.groupby("Menu type")["Actual meals sold"].sum()
    top_menu = str(menu_totals.idxmax())

    waste_pct = waste_summary.get("avg_waste_pct", 0.0) if waste_summary else 0.0
    total_discarded = waste_summary.get("total_discarded", 0) if waste_summary else 0

    return {
        "total_records": total_records,
        "unique_dates": unique_dates,
        "menu_categories": MENU_TYPES,
        "date_range_start": date_min,
        "date_range_end": date_max,
        "avg_daily_demand": avg_daily_demand,
        "top_menu_by_demand": top_menu,
        "avg_waste_percentage": waste_pct,
        "total_discarded_recorded": total_discarded,
        "dataset_disclaimer": "All historical records are generated by a reproducible canteen demand simulator. Suitable for prototype testing and planning simulation.",
        "model_status": "Ready & Loaded"
    }


def query_historical_records(
    menu_type: Optional[str] = None,
    day_of_week: Optional[str] = None,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    limit: int = 200
) -> List[Dict[str, Any]]:
    df = get_historical_dataframe()

    if menu_type and menu_type != "All":
        df = df[df["Menu type"] == menu_type]
    if day_of_week and day_of_week != "All":
        df = df[df["Day of week"] == day_of_week]
    if start_date:
        df = df[df["Date"] >= pd.to_datetime(start_date)]
    if end_date:
        df = df[df["Date"] <= pd.to_datetime(end_date)]

    # Limit to most recent or first `limit` rows
    df_sorted = df.sort_values(by="Date", ascending=False).head(limit)

    records = []
    for _, row in df_sorted.iterrows():
        records.append({
            "date": row["Date"].strftime("%Y-%m-%d"),
            "day_of_week": row["Day of week"],
            "menu_type": row["Menu type"],
            "expected_attendance": int(row["Expected attendance"]),
            "temperature": float(row["Temperature"]),
            "prev_day_sales": float(row["Previous day's sales"]),
            "is_holiday": int(row["Holiday indicator"]),
            "actual_meals_sold": int(row["Actual meals sold"])
        })
    return records


def get_analytics_charts_data(menu_type: Optional[str] = None) -> Dict[str, Any]:
    df = get_historical_dataframe()

    filtered_df = df if (not menu_type or menu_type == "All") else df[df["Menu type"] == menu_type]

    # 1. Daily demand trend (last 60 days for smooth, uncluttered rendering)
    recent_dates = filtered_df["Date"].drop_duplicates().sort_values().tail(45)
    recent_df = filtered_df[filtered_df["Date"].isin(recent_dates)]
    
    daily_trend = []
    for dt, group in recent_df.groupby("Date"):
        entry: Dict[str, Any] = {
            "date": dt.strftime("%b %d"),
            "total_meals": int(group["Actual meals sold"].sum()),
            "avg_attendance": int(group["Expected attendance"].mean())
        }
        for m in MENU_TYPES:
            m_rows = group[group["Menu type"] == m]
            if not m_rows.empty:
                entry[m] = int(m_rows["Actual meals sold"].values[0])
        daily_trend.append(entry)

    # 2. Average demand by weekday
    weekday_order = {day: idx for idx, day in enumerate(WEEKDAYS)}
    weekday_summary = []
    for day in WEEKDAYS:
        day_rows = filtered_df[filtered_df["Day of week"] == day]
        if not day_rows.empty:
            avg_sold = round(float(day_rows["Actual meals sold"].mean()), 1)
            total_sold = int(day_rows["Actual meals sold"].sum())
            weekday_summary.append({
                "day": day[:3],
                "full_day": day,
                "avg_meals": avg_sold,
                "total_meals": total_sold
            })

    # 3. Demand by menu type
    menu_summary = []
    menu_grouped = df.groupby("Menu type")["Actual meals sold"].agg(["sum", "mean", "count"]).reset_index()
    total_all_meals = menu_grouped["sum"].sum()
    for _, row in menu_grouped.iterrows():
        menu_summary.append({
            "menu_type": row["Menu type"],
            "total_meals": int(row["sum"]),
            "avg_meals": round(float(row["mean"]), 1),
            "share_percent": round(float((row["sum"] / total_all_meals) * 100), 1)
        })

    # 4. Attendance versus meals sold (sampled to 100 points for clean scatter)
    scatter_sample = filtered_df.sample(n=min(120, len(filtered_df)), random_state=42)
    attendance_vs_sales = [
        {
            "attendance": int(row["Expected attendance"]),
            "meals_sold": int(row["Actual meals sold"]),
            "menu_type": row["Menu type"],
            "is_holiday": int(row["Holiday indicator"])
        }
        for _, row in scatter_sample.iterrows()
    ]

    return {
        "daily_trend": daily_trend,
        "weekday_demand": weekday_summary,
        "menu_breakdown": menu_summary,
        "attendance_vs_sales": attendance_vs_sales
    }
